### ISSUE TITLE
Please publish chefdk 3.12.10 to chocolatey

### ISSUE THREAD

**Issue by PartTimeLegend** [chef/chocolatey-packages#19]
I need this for a legacy setup that I am trying to fix.

**Comment by clintoncwolfe** [comment]
zipfile posted in community slack https://chefcommunity.slack.com/archives/C0M1NGZE3/p1586359223026600

**Comment by PartTimeLegend** [comment]
Likely to happen?

**Comment by tas50** [comment]
Closing this out since it's EOL
